// File generated by Antigravity to support Firebase/Web initialization

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6cY5eezF-4--k_opfvTi61TEc6bAPVsk',
    appId: '1:868273007836:web:1584c0c1737e500b471819', // Generic placeholder, usually not critical if authDomain is correct for Auth
    messagingSenderId: '868273007836',
    projectId: 'careertwin-ai',
    authDomain: 'careertwin-ai.firebaseapp.com',
    storageBucket: 'careertwin-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6cY5eezF-4--k_opfvTi61TEc6bAPVsk',
    appId: '1:868273007836:android:73d2bb007c471649471819',
    messagingSenderId: '868273007836',
    projectId: 'careertwin-ai',
    storageBucket: 'careertwin-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6cY5eezF-4--k_opfvTi61TEc6bAPVsk',
    appId: '1:868273007836:ios:e31846b04856037e471819', // Placeholder if not provided
    messagingSenderId: '868273007836',
    projectId: 'careertwin-ai',
    storageBucket: 'careertwin-ai.firebasestorage.app',
    iosBundleId: 'ai.careertwin.mobile',
  );
}
